apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: helloshashank2
  name: helloshashank2
spec:
  containers:
  - image: alpine
    name: helloshashank2
    command: ["/bin/sh","-c"]
    args:
    - "sleep infinity"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}

# kubectl get pods -n shashank -o wide | awk '{print$6}' | grep 192* > IP.txt
# kubectl cp IP.txt shashank/helloshashank2:/root/IP.txt
