apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: helloshashank1
  name: helloshashank1
spec:
  containers:
  - image: busybox
    name: helloshashank1
    workingDir: /opt
    command: ["/bin/sh","-c"]
    args:
    - "sleep infinity"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}

# kubectl cp shashank/helloshashank:/tmp/adhoc.txt adhoc.txt
# kubectl cp adhoc.txt shashank/helloshashank1:/opt
# kubectl exec helloshashank1 -n shashank -- /bin/sh -c "cat adhoc.txt | wc -c > count.txt"
